In [1]:
# ==== M1: Merge comments + posts -> stage1_clean_{Sub}.jsonl (with Palia support) ====
from pathlib import Path
import pandas as pd
import json, re, unicodedata
from typing import Any, Dict, Optional

# --------- FILES from your original setup ---------
FILES = {
    "ElderScrollsOnline": {
        "comments": "r_ElderScrollsOnline_comments.csv",
        "posts":    "r_ElderScrollsOnline_posts.jsonl",
    },
    "WoW": {
        "comments": "r_WoW_comments.csv",
        "posts":    "r_WoW_posts.jsonl",
    },
    "SkyChildrenoftheLight": {
        "comments": "r_sky_comments.csv",  # note: your comments file is 'r_sky_comments.csv'
        "posts":    "r_SkyChildrenoftheLight_posts.jsonl",
    },
    "AlbionOnline": {
        "comments": "r_AlbionOnline_comments.csv",
        "posts":    "r_AlbionOnline_posts.jsonl",
    },
    "DarkSouls": {
        "comments": "r_DarkSouls_comments.csv",
        "posts":    "r_DarkSouls_posts.jsonl",
    },
    "LiesofP": {
        "comments": "r_LiesofP_comments.csv",
        "posts":    "r_LiesofP_posts.jsonl",
    },
    "HollowKnight": {
        "comments": "r_HollowKnight_comments.csv",
        "posts":    "r_HollowKnight_posts.jsonl",
    },
    "Ninesols": {
        "comments": "r_Ninesols_comments.csv",
        "posts":    "r_Ninesols_posts.jsonl",
    },
}

# --------- ADD PALIA (JSONL comments + JSONL posts) ---------
FILES["Palia"] = {
    "comments_jsonl": "r_Palia_comments.jsonl",   # JSONL comments
    "posts":          "r_Palia_posts.jsonl",      # JSONL posts
}

# --------- text cleaning tuned for moderation ---------
URL_RE  = re.compile(r"(https?://\S+)|(\[.*?\]\(https?://\S+?\))", re.I)
CODE_RE = re.compile(r"`{1,3}.*?`{1,3}", re.S)
EMPH_RE = re.compile(r"(\*{1,3}|_{1,3})")
WS_RE   = re.compile(r"\s+")

def nfkc(s: str) -> str: 
    return unicodedata.normalize("NFKC", s)

def clean_text_for_moderation(s: Any) -> str:
    if not isinstance(s, str): 
        return ""
    s = nfkc(s).lower()
    s = CODE_RE.sub(" ", s)
    s = URL_RE.sub(" ", s)
    s = (s.replace("&gt;", ">")
           .replace("&lt;", "<")
           .replace("&amp;", "&")
           .replace("&nbsp;", " "))
    s = EMPH_RE.sub(" ", s)
    s = WS_RE.sub(" ", s).strip()
    return s

def strip_prefix(x: Optional[str]) -> Optional[str]:
    if x is None: 
        return None
    s = str(x)
    return s.split("_", 1)[-1] if "_" in s else s

def split_parent(pid: Optional[str]) -> tuple[Optional[str], Optional[str]]:
    if not pid or not isinstance(pid, str): 
        return None, None
    parts = pid.split("_", 1)
    if len(parts) == 2: 
        return parts[0], parts[1]
    return None, parts[0]

def coerce_int(v) -> Optional[int]:
    try: 
        return int(v)
    except Exception: 
        return None

def is_deleted_author(a: Any) -> bool:
    return isinstance(a, str) and a.strip().lower() == "[deleted]"

REQUIRED = [
    "subreddit","post_id","title","comment_id","parent_id",
    "author","body","created_utc","score","flair","link_id"
]

# --------- normalizers (comment rows, post rows) ---------
def normalize_comment_row(row: Dict[str, Any]) -> tuple[Dict[str, Any], bool]:
    # Must have a non-empty comment_id to be a comment
    comment_id = row.get("comment_id") or row.get("id")
    if not comment_id or str(comment_id).strip() == "":
        return {}, True

    post_id_bare = strip_prefix(row.get("post_id") or row.get("link_id"))
    comm_id_bare = strip_prefix(comment_id)
    link_id_bare = strip_prefix(row.get("link_id"))
    parent_id    = row.get("parent_id")
    parent_kind, parent_key = split_parent(parent_id)

    title_raw = row.get("title")
    body_raw  = row.get("body") or row.get("selftext") or ""
    title_clean = clean_text_for_moderation(title_raw) if isinstance(title_raw, str) else None
    body_clean  = clean_text_for_moderation(body_raw)

    # drop rules for comments only
    drop = False
    if is_deleted_author(row.get("author")):
        drop = True
    if isinstance(body_raw, str) and body_raw.strip().lower() in {"[deleted]","[removed]"}:
        drop = True
    if len(body_clean) == 0:
        drop = True

    out = {
        "subreddit": (row.get("subreddit") or "").strip().lower() or None,
        "post_id": post_id_bare,
        "title": title_clean,  # comments typically have None title; harmless
        "comment_id": comm_id_bare,
        "parent_id": parent_id,
        "author": (row.get("author") or "").strip().lower() or None,
        "body_raw": body_raw,
        "body": body_clean,
        "created_utc": coerce_int(row.get("created_utc")),
        "score": row.get("score"),
        "flair": row.get("flair"),
        "link_id": link_id_bare,
        "parent_kind": parent_kind,
        "parent_key": parent_key,
        "record_type": "comment",
    }
    for k in REQUIRED:
        out.setdefault(k, None)
    return out, drop

def normalize_post_row(row: Dict[str, Any], subreddit_hint: Optional[str]=None) -> Dict[str, Any]:
    # Posts come from JSONL; map common field names
    pid = row.get("post_id") or row.get("id") or row.get("link_id")
    pid = strip_prefix(pid)
    title_raw = row.get("title") or row.get("link_title")
    body_raw  = (
        row.get("selftext") if "selftext" in row
        else row.get("body")
        or row.get("text")
        or row.get("content")
        or ""
    )
    author    = row.get("author")
    created   = row.get("created_utc") or row.get("created") or row.get("createdUtc")
    score     = row.get("score") or row.get("ups")
    flair     = row.get("link_flair_text") if "link_flair_text" in row else row.get("flair")

    title_clean = clean_text_for_moderation(title_raw) if isinstance(title_raw, str) else None
    body_clean  = clean_text_for_moderation(body_raw)

    subreddit_norm = (row.get("subreddit") or subreddit_hint or "").strip().lower() or None
    author_norm    = (author or "").strip().lower() or None

    # For posts, set parent to itself (root) with t3_
    parent_id = f"t3_{pid}" if pid else None
    parent_kind, parent_key = split_parent(parent_id)

    out = {
        "subreddit": subreddit_norm,
        "post_id": pid,
        "title": title_clean,
        "comment_id": None,
        "parent_id": parent_id,
        "author": author_norm,
        "body_raw": body_raw,
        "body": body_clean,
        "created_utc": coerce_int(created),
        "score": score,
        "flair": flair,
        "link_id": pid,          # root link for thread
        "parent_kind": parent_kind,  # 't3'
        "parent_key": parent_key,
        "record_type": "post",
    }
    for k in REQUIRED:
        out.setdefault(k, None)
    return out

# --------- merge runner (supports CSV or JSONL comments) ---------
def merge_one_sub(sub: str, paths: Dict[str, str], out_path: Path, chunksize: int = 200_000):
    kept_posts = kept_comments = dropped_comments = 0
    rows_in_comments = rows_in_posts = 0

    with out_path.open("w", encoding="utf-8") as fout:

        # 1) COMMENTS from CSV (most subs)
        if "comments" in paths:
            comments_csv = Path(paths["comments"])
            if comments_csv.exists():
                for chunk in pd.read_csv(comments_csv, chunksize=chunksize):
                    rows_in_comments += len(chunk)
                    for row in chunk.to_dict(orient="records"):
                        rec, drop = normalize_comment_row(row)
                        if not rec:
                            continue
                        if drop:
                            dropped_comments += 1
                            continue
                        fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        kept_comments += 1
            else:
                print(f"[{sub}] WARNING: comments CSV not found → {comments_csv}")

        # 2) COMMENTS from JSONL (Palia)
        elif "comments_jsonl" in paths:
            comments_jsonl = Path(paths["comments_jsonl"])
            if comments_jsonl.exists():
                with comments_jsonl.open("r", encoding="utf-8") as f:
                    for line in f:
                        if not line.strip():
                            continue
                        rows_in_comments += 1
                        row = json.loads(line)
                        rec, drop = normalize_comment_row(row)
                        if not rec:
                            continue
                        if drop:
                            dropped_comments += 1
                            continue
                        fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        kept_comments += 1
            else:
                print(f"[{sub}] WARNING: comments JSONL not found → {comments_jsonl}")

        # 3) POSTS (JSONL for all subs)
        posts_jsonl = Path(paths["posts"])
        if posts_jsonl.exists():
            with posts_jsonl.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    rows_in_posts += 1
                    row = json.loads(line)
                    rec = normalize_post_row(row, subreddit_hint=sub)
                    fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    kept_posts += 1
        else:
            print(f"[{sub}] WARNING: posts file not found → {posts_jsonl}")

    print(f"[{sub}] wrote → {out_path}")
    print(f"[{sub}] comments_in={rows_in_comments:,} | comments_kept={kept_comments:,} | comments_dropped={dropped_comments:,}")
    print(f"[{sub}] posts_in={rows_in_posts:,} | posts_kept={kept_posts:,}")

# --------- run for all subs (including Palia) ---------
for sub, paths in FILES.items():
    out_path = Path(f"stage1_clean_{sub}.jsonl")
    merge_one_sub(sub, paths, out_path)

[ElderScrollsOnline] wrote → stage1_clean_ElderScrollsOnline.jsonl
[ElderScrollsOnline] comments_in=53,483 | comments_kept=52,633 | comments_dropped=850
[ElderScrollsOnline] posts_in=2,711 | posts_kept=2,711
[WoW] wrote → stage1_clean_WoW.jsonl
[WoW] comments_in=381,802 | comments_kept=375,361 | comments_dropped=6,441
[WoW] posts_in=12,442 | posts_kept=12,442
[SkyChildrenoftheLight] WARNING: comments CSV not found → r_sky_comments.csv
[SkyChildrenoftheLight] WARNING: posts file not found → r_SkyChildrenoftheLight_posts.jsonl
[SkyChildrenoftheLight] wrote → stage1_clean_SkyChildrenoftheLight.jsonl
[SkyChildrenoftheLight] comments_in=0 | comments_kept=0 | comments_dropped=0
[SkyChildrenoftheLight] posts_in=0 | posts_kept=0
[AlbionOnline] wrote → stage1_clean_AlbionOnline.jsonl
[AlbionOnline] comments_in=23,663 | comments_kept=23,086 | comments_dropped=577
[AlbionOnline] posts_in=2,191 | posts_kept=2,191
[DarkSouls] wrote → stage1_clean_DarkSouls.jsonl
[DarkSouls] comments_in=29,098 | comments_kept=28,709 | comments_dropped=389
[DarkSouls] posts_in=2,272 | posts_kept=2,272
[LiesofP] wrote → stage1_clean_LiesofP.jsonl
[LiesofP] comments_in=48,854 | comments_kept=48,213 | comments_dropped=641
[LiesofP] posts_in=2,869 | posts_kept=2,869
[HollowKnight] wrote → stage1_clean_HollowKnight.jsonl
[HollowKnight] comments_in=449,393 | comments_kept=445,496 | comments_dropped=3,897
[HollowKnight] posts_in=43,418 | posts_kept=43,418
[Ninesols] wrote → stage1_clean_Ninesols.jsonl
[Ninesols] comments_in=8,687 | comments_kept=8,150 | comments_dropped=537
[Ninesols] posts_in=648 | posts_kept=648
[Palia] wrote → stage1_clean_Palia.jsonl
[Palia] comments_in=76,633 | comments_kept=75,136 | comments_dropped=1,497
[Palia] posts_in=5,022 | posts_kept=5,022

In [2]:
# ==== Stage 2: Parent + Root Enrichment for all subs ====
from pathlib import Path
import json

SUBS = [
    "Palia"
]

def enrich_one_sub(sub: str):
    in_path  = Path(f"stage1_clean_{sub}.jsonl")
    out_path = Path(f"clean_enriched_{sub}.jsonl")
    assert in_path.exists(), f"[{sub}] missing input: {in_path}"

    # ---- Pass 1: build minimal lookup maps ----
    posts_by_id    = {}  # post_id -> {title, body, author, created_utc}
    comments_by_id = {}  # comment_id -> {body, author, parent_id, link_id, created_utc}

    with in_path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("record_type") == "post":
                pid = r.get("post_id")
                if pid:
                    posts_by_id[pid] = {
                        "title": r.get("title"),
                        "body": r.get("body"),
                        "author": r.get("author"),
                        "created_utc": r.get("created_utc"),
                    }
            elif r.get("record_type") == "comment":
                cid = r.get("comment_id")
                if cid:
                    comments_by_id[cid] = {
                        "body": r.get("body"),
                        "author": r.get("author"),
                        "parent_id": r.get("parent_id"),
                        "link_id": r.get("link_id"),
                        "created_utc": r.get("created_utc"),
                    }

    # ---- helpers ----
    def parent_lookup(rec):
        """Return (ptype, pbody, pauthor, pmissing)."""
        kind = rec.get("parent_kind")
        key  = rec.get("parent_key")
        if not key:
            return ("missing", None, None, True)

        if kind == "t1":
            p = comments_by_id.get(key)
            if p:
                return ("comment", p.get("body"), p.get("author"), False)
            else:
                return ("comment", None, None, True)

        if kind == "t3":
            p = posts_by_id.get(key)
            if p:
                # prefer post body; if missing, fall back to title
                pbody = p.get("body") or p.get("title")
                return ("post", pbody, p.get("author"), False)
            else:
                return ("post", None, None, True)

        if kind == "t2":
            # reply-to-user (rare) — no text attachable
            return ("user", None, None, True)

        return ("missing", None, None, True)

    def root_lookup(rec):
        """Return (root_post_id, root_title, root_author, root_missing)."""
        rid = rec.get("link_id")
        if not rid:
            return (None, None, None, True)
        p = posts_by_id.get(rid)
        if p:
            return (rid, p.get("title"), p.get("author"), False)
        # keep structural root even if metadata absent
        return (rid, None, None, False)

    # ---- Pass 2: enrich + write ----
    n_in = n_out = 0
    parent_types = {"comment":0, "post":0, "user":0, "missing":0}
    root_missing_ct = 0

    with in_path.open("r", encoding="utf-8") as fin, out_path.open("w", encoding="utf-8") as fout:
        for line in fin:
            if not line.strip():
                continue
            rec = json.loads(line)
            n_in += 1

            # root info
            root_post_id, root_title, root_author, root_missing = root_lookup(rec)
            if root_missing:
                root_missing_ct += 1
            rec["root_post_id"] = root_post_id
            rec["root_title"]   = root_title
            rec["root_author"]  = root_author
            rec["root_missing"] = root_missing

            # parent info (always attach fields; meaningful for comments)
            ptype, pbody, pauthor, pmissing = parent_lookup(rec)
            rec["parent_record_type"] = ptype
            rec["parent_body"]        = pbody
            rec["parent_author"]      = pauthor
            rec["parent_missing"]     = pmissing
            if rec.get("record_type") == "comment":
                parent_types[ptype] = parent_types.get(ptype,0) + 1

            fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
            n_out += 1

    print(f"[{sub}] Enrichment: read {n_in:,} → wrote {n_out:,} → {out_path.name}")
    print(f"[{sub}] Comment parent types: {parent_types}")
    print(f"[{sub}] Root missing count: {root_missing_ct:,}\n")

for sub in SUBS:
    enrich_one_sub(sub)

[Palia] Enrichment: read 80,158 → wrote 80,158 → clean_enriched_Palia.jsonl
[Palia] Comment parent types: {'comment': 39109, 'post': 36027, 'user': 0, 'missing': 0}
[Palia] Root missing count: 0

In [15]:
%pip install python-dotenv -q
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv(), override=True)
print(os.getenv("OPENAI_API_KEY"))

Note: you may need to restart the kernel to use updated packages.
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

In [16]:
import os
import json
import time
from pathlib import Path
from openai import OpenAI
from tqdm import tqdm

# create client (it reads your OPENAI_API_KEY automatically)
client = OpenAI()

print("✅ OpenAI client initialized successfully.")

✅ OpenAI client initialized successfully.

In [17]:
# ==== Stage 3 (corrected): Moderation scoring, batched + resumable ====
from pathlib import Path
import json, time, random, os
from typing import List, Dict, Any
from openai import OpenAI

client = OpenAI()  # uses OPENAI_API_KEY from env

def rec_key(r: Dict[str, Any]) -> str:
    # stable unique key per record
    if r.get("record_type") == "comment":
        return f"t1_{r.get('comment_id')}"
    return f"t3_{r.get('post_id')}"

def build_text(r: Dict[str, Any]) -> str:
    # posts: body or fallback to title; comments: body
    return (r.get("body") or (r.get("title") if r.get("record_type")=="post" else "") or "").strip()

def load_done(state_path: Path) -> set:
    if state_path.exists():
        try: return set(json.loads(state_path.read_text(encoding="utf-8")))
        except: return set()
    return set()

def save_done(done: set, state_path: Path):
    state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")

def moderations_batch(texts: List[str]) -> List[Dict[str, Any]]:
    resp = client.moderations.create(model="omni-moderation-latest", input=texts)
    results = getattr(resp, "results", resp)
    out = []
    for r in results:
        out.append({
            "toxicity_flag": bool(r.flagged),
            "toxicity_categories": dict(r.categories),
            "toxicity_scores": dict(r.category_scores),
        })
    return out

def score_file_batched(
    in_path: Path,
    out_path: Path,
    state_path: Path,
    types_to_score=("comment","post"),
    batch_size=32,          # you can raise this after confirming RPM
    base_sleep=0.2,         # small pause between batches (paid accounts handle this fine)
    max_retries=5,
):
    assert in_path.exists(), f"Missing input: {in_path}"
    done = load_done(state_path)

    def flush(batch_rows: List[Dict[str,Any]], batch_texts: List[str]):
        # retry with exponential backoff on 429s/temporary errors
        for attempt in range(max_retries):
            try:
                scores = moderations_batch(batch_texts)
                break
            except Exception as e:
                wait = (2 ** attempt) + random.random()
                print(f"API retry ({attempt+1}/{max_retries}) after error: {e} → wait {wait:.1f}s")
                time.sleep(wait)
        else:
            # give up on this batch; write passthrough records without scores
            scores = [None]*len(batch_rows)

        with out_path.open("a", encoding="utf-8") as fout:
            for rec, sc in zip(batch_rows, scores):
                if sc:
                    rec.update(sc)
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                done.add(rec["__key"])
        save_done(done, state_path)
        time.sleep(base_sleep)

    total_in = 0
    batch_rows, batch_texts = [], []
    with in_path.open("r", encoding="utf-8") as fin:
        for line in fin:
            line = line.strip()
            if not line: continue
            rec = json.loads(line)
            total_in += 1

            if rec.get("record_type") not in types_to_score:
                continue
            text = build_text(rec)
            if not text:
                continue

            key = rec_key(rec)
            if key in done:
                continue

            rec["__key"] = key
            batch_rows.append(rec)
            batch_texts.append(text)

            if len(batch_rows) >= batch_size:
                flush(batch_rows, batch_texts)
                batch_rows, batch_texts = [], []

    # tail
    if batch_rows:
        flush(batch_rows, batch_texts)

    # count out
    out_count = 0
    if out_path.exists():
        with out_path.open("r", encoding="utf-8") as f:
            for _ in f: out_count += 1

    return total_in, len(done), out_count

In [18]:
def get_moderation_score(text, model="omni-moderation-latest"):
    """Send text to OpenAI moderation model and return the results safely."""
    try:
        response = client.moderations.create(model=model, input=text)
        result = response.results[0]
        return {
            "flagged": result.flagged,
            "categories": result.categories,
            "category_scores": result.category_scores
        }
    except Exception as e:
        print("Error:", e)
        return None

In [26]:
from openai import OpenAI
client = OpenAI()
resp = client.moderations.create(model="omni-moderation-latest", input="test message")
print("OK:", bool(resp.results[0].categories))

OK: True

In [28]:
# ==== Stage 3 (token-aware, adaptive, resumable) ====
from pathlib import Path
from typing import Dict, Any, List, Tuple, Iterable, Set
import json, time, random, os, re

from openai import OpenAI
client = OpenAI()  # uses OPENAI_API_KEY

# --- config knobs you can tweak ---
CHAR_BUDGET_PER_REQUEST = 32000   # ~8k tokens (≈4 chars/token)
PER_ITEM_CHAR_CAP       = 2000    # cap each text ~500 tokens
MIN_BATCH               = 4
MAX_BATCH               = 16       # raise to 32 later when stable
START_BATCH             = 4
START_SLEEP_S           = 0.2      # short pause between batches
MAX_SLEEP_S             = 5.0

# --- utils ---
def read_jsonl(p: Path) -> Iterable[Dict[str,Any]]:
    with p.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)

def rec_key(r: Dict[str, Any]) -> str:
    return f"t1_{r['comment_id']}" if r.get("record_type") == "comment" else f"t3_{r['post_id']}"

_ws_re = re.compile(r"\s+")
def build_text(r: Dict[str, Any]) -> str:
    # posts: prefer body else title; comments: body
    txt = (r.get("body") or (r.get("title") if r.get("record_type")=="post" else "") or "")
    # normalize
    txt = txt.strip()
    txt = _ws_re.sub(" ", txt)
    # hard truncate to reduce tokens (moderation doesn’t need the whole thing)
    if len(txt) > PER_ITEM_CHAR_CAP:
        txt = txt[:PER_ITEM_CHAR_CAP]
    return txt

def load_done(p: Path) -> Set[str]:
    if not p.exists(): return set()
    try: return set(json.loads(p.read_text(encoding="utf-8")))
    except: return set()

def save_done(done: Set[str], p: Path):
    p.write_text(json.dumps(sorted(done)), encoding="utf-8")

def moderations_batch(texts: List[str]) -> List[Dict[str, Any]]:
    resp = client.moderations.create(model="omni-moderation-latest", input=texts)
    results = getattr(resp, "results", resp)
    out = []
    for r in results:
        out.append({
            "toxicity_flag": bool(r.flagged),
            "toxicity_categories": dict(r.categories),
            "toxicity_scores": dict(r.category_scores),
        })
    return out

def score_file_adaptive_token_aware(
    in_path: Path,
    out_path: Path,
    state_path: Path,
    types_to_score: Tuple[str, ...] = ("comment","post"),
    initial_batch_size: int = START_BATCH,
    min_batch_size: int = MIN_BATCH,
    max_batch_size: int = MAX_BATCH,
    initial_sleep: float = START_SLEEP_S,
    max_retries: int = 6,
) -> Tuple[int,int,int]:
    assert in_path.exists(), f"Missing input: {in_path}"
    done = load_done(state_path)

    batch_size = initial_batch_size
    sleep_s = initial_sleep
    consecutive_ok = 0

    def flush(rows: List[Dict[str,Any]], texts: List[str]):
        nonlocal batch_size, sleep_s, consecutive_ok
        for attempt in range(max_retries):
            try:
                scores = moderations_batch(texts)
                # success → gently speed up
                consecutive_ok += 1
                if consecutive_ok >= 5 and batch_size < max_batch_size:
                    batch_size = min(max_batch_size, batch_size + 2)  # small ramp
                    consecutive_ok = 0
                # nudge sleep down (not below 0.05)
                if sleep_s > 0.05:
                    sleep_s = max(0.05, sleep_s * 0.8)
                break
            except Exception as e:
                msg = str(e)
                if "429" in msg or "Too Many Requests" in msg or "503" in msg or "500" in msg:
                    wait = 5 * (2 ** attempt) + random.random()  # 5,10,20,40...
                    print(f"[{in_path.name}] retry {attempt+1}/{max_retries} "
                          f"(batch={len(texts)}, sleep={sleep_s:.2f}s) after {wait:.1f}s: {e}")
                    # slow down + shrink batch on errors
                    consecutive_ok = 0
                    sleep_s = min(MAX_SLEEP_S, sleep_s * 1.5 + 0.25)
                    batch_size = max(min_batch_size, max(min_batch_size, batch_size - 2))
                    time.sleep(wait)
                    continue
                else:
                    print(f"[{in_path.name}] non-retriable error, writing passthrough: {e}")
                    scores = [None] * len(rows)
                    break

        with out_path.open("a", encoding="utf-8") as fout:
            for rec, sc in zip(rows, scores):
                if sc:
                    rec.update(sc)
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                done.add(rec["__key"])
        save_done(done, state_path)
        if sleep_s: time.sleep(sleep_s)

    total_seen = 0
    # build batches that respect a char budget (≈ token budget)
    pending_rows, pending_texts = [], []
    pending_chars = 0

    for rec in read_jsonl(in_path):
        total_seen += 1
        if rec.get("record_type") not in types_to_score:
            continue
        txt = build_text(rec)
        if not txt:
            continue

        key = rec_key(rec)
        if key in done:
            continue

        rec["__key"] = key
        # If adding this text would exceed budget or batch_size, flush first
        if pending_rows and (pending_chars + len(txt) > CHAR_BUDGET_PER_REQUEST or len(pending_rows) >= batch_size):
            flush(pending_rows, pending_texts)
            pending_rows, pending_texts, pending_chars = [], [], 0

        pending_rows.append(rec)
        pending_texts.append(txt)
        pending_chars += len(txt)

    if pending_rows:
        flush(pending_rows, pending_texts)

    out_count = 0
    if out_path.exists():
        with out_path.open("r", encoding="utf-8") as f:
            for _ in f: out_count += 1

    print(f"[{in_path.name}] token-aware adaptive done → batch≤{batch_size}, sleep≈{sleep_s:.2f}s")
    return total_seen, len(done), out_count

In [33]:
# ==== Stage 3: Single-input, resume-safe scorer (with limit_rows) ====
from pathlib import Path
import json, time
from openai import OpenAI

client = OpenAI()

def rec_key(r): 
    return f"t1_{r['comment_id']}" if r.get("record_type")=="comment" else f"t3_{r['post_id']}"

def text_of(r):
    # posts: prefer body else title; comments: body; normalize + truncate
    txt = (r.get("body") or (r.get("title") if r.get("record_type")=="post" else "") or "").strip()
    if len(txt) > 2000:  # ~500 tokens
        txt = txt[:2000]
    return txt

def score_file_single(
    in_path: Path,
    out_path: Path,
    state_path: Path,
    start_sleep: float = 1.0,
    min_sleep: float = 0.2,
    max_sleep: float = 5.0,
    limit_rows: int | None = None,     # <-- NEW: cap how many records to process
    types_to_score=("comment","post")  # optional: restrict to comments OR posts
):
    # load checkpoint
    done = set()
    if state_path.exists():
        try:
            done = set(json.loads(state_path.read_text(encoding="utf-8")))
        except:
            pass

    sleep_s = start_sleep
    n_seen = n_done = n_out = n_iter = 0

    with in_path.open("r", encoding="utf-8") as fin, out_path.open("a", encoding="utf-8") as fout:
        for line in fin:
            if limit_rows is not None and n_iter >= limit_rows:
                break  # stop early for a fast test
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            n_iter += 1

            if rec.get("record_type") not in types_to_score:
                # still write-through to keep file alignment if you prefer; for test we just skip
                continue

            n_seen += 1
            key = rec_key(rec)
            if key in done:
                continue

            txt = text_of(rec)
            if not txt:
                # write passthrough to keep indices aligned
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n_out += 1
                done.add(key)
                state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")
                continue

            # single-input moderation call (avoids array batching)
            try:
                resp = client.moderations.create(model="omni-moderation-latest", input=txt)
                r0 = resp.results[0]
                rec.update({
                    "toxicity_flag": bool(r0.flagged),
                    "toxicity_categories": dict(r0.categories),
                    "toxicity_scores": dict(r0.category_scores),
                })
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n_done += 1; n_out += 1; done.add(key)
                state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")

                # gentle pacing: if no recent 429s, nudge faster; otherwise we’ll slow via except
                sleep_s = max(min_sleep, sleep_s * 0.9)
                time.sleep(sleep_s)

            except Exception as e:
                msg = str(e)
                if "429" in msg or "Too Many Requests" in msg or "rate" in msg.lower():
                    # slow down and retry once
                    sleep_s = min(max_sleep, sleep_s * 1.7 + 0.5)
                    time.sleep(sleep_s)
                    continue
                else:
                    # non-retriable: skip this record but keep pipeline moving
                    print("Non-429 error; skipping one record:", e)
                    fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    n_out += 1
                    done.add(key)
                    state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")

    return n_seen, n_done, n_out

In [40]:
from pathlib import Path
sub = "ElderScrollsOnline"
for p in [Path(f"scored_{sub}.TEST.__keys.json"), Path(f"scored_{sub}.TEST.jsonl")]:
    if p.exists():
        p.unlink()   # deletes the file

In [46]:
from pathlib import Path
import json

sub = "ElderScrollsOnline"
path = Path(f"clean_enriched_{sub}.jsonl")

counts = {"post":0, "comment":0}
with path.open("r", encoding="utf-8") as f:
    for line in f:
        r = json.loads(line)
        rt = r.get("record_type")
        if rt in counts:
            counts[rt] += 1

counts

{'post': 2711, 'comment': 52633}

In [50]:
sub = "ElderScrollsOnline"
n_seen, n_done, n_out = score_file_single(
    in_path=Path(f"clean_enriched_{sub}.jsonl"),
    out_path=Path(f"scored_{sub}.TEST.jsonl"),
    state_path=Path(f"scored_{sub}.TEST.__keys.json"),
    start_sleep=1.0,
    limit_rows=50000,                 # was 25 → try 500
    types_to_score=("post",)     # keep comments for now
)
print(f"{sub}: seen={n_seen}  newly_scored={n_done}  out_total(additions)={n_out}")

ElderScrollsOnline: seen=0  newly_scored=0  out_total(additions)=0

In [43]:
n_seen, n_done, n_out = score_file_single(
    Path(f"clean_enriched_{sub}.jsonl"),
    Path(f"scored_{sub}.TEST.jsonl"),
    Path(f"scored_{sub}.TEST.__keys.json"),
    start_sleep=1.0,
    limit_rows=300,                 # a smaller posts sample
    types_to_score=("post",)
)
print(f"{sub}: seen={n_seen}  newly_scored={n_done}  out_total(additions)={n_out}")

ElderScrollsOnline: seen=0  newly_scored=0  out_total(additions)=0

In [51]:
sub = "Ninesols"
n_seen, n_done, n_out = score_file_single(
    Path(f"clean_enriched_{sub}.jsonl"),
    Path(f"scored_{sub}.jsonl"),
    Path(f"scored_{sub}.__keys.json"),
    start_sleep=1.0,                     # safe pacing
    limit_rows=300,                      # small pilot
    types_to_score=("comment","post")
)
print(f"{sub}: seen={n_seen:,} newly_scored={n_done:,} out_total={n_out:,}")

KeyboardInterrupt:

In [56]:
# Small, randomized probe (fast)
from pathlib import Path
import json, time, re, random
from typing import Dict, Any, List, Tuple
from openai import OpenAI
from tqdm import tqdm

client = OpenAI()
_ws = re.compile(r"\s+")

def _text_of(r, cap=2000):
    txt = (r.get("body") or (r.get("title") if r.get("record_type")=="post" else "") or "")
    return _ws.sub(" ", txt.strip())[:cap]

def reservoir_sample_jsonl(path: Path, k: int, types=("comment","post")) -> List[Dict[str,Any]]:
    """Reservoir sample k rows matching record types."""
    sample, n = [], 0
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip(): continue
            r = json.loads(line)
            if r.get("record_type") not in types: continue
            txt = _text_of(r)
            if not txt: continue
            r["__txt"] = txt
            n += 1
            if len(sample) < k:
                sample.append(r)
            else:
                j = random.randint(1, n)
                if j <= k:
                    sample[j-1] = r
    return sample

def small_speed_probe(sub: str, rows_comment=150, rows_post=50,
                      sleeps=(0.20, 0.15, 0.12, 0.10)) -> List[Tuple[str,float,int,int,float]]:
    results = []
    for kind, rows in (("comment", rows_comment), ("post", rows_post)):
        src = Path(f"clean_enriched_{sub}.jsonl")
        sample = reservoir_sample_jsonl(src, k=rows, types=(kind,))
        if not sample:
            print(f"[probe] No {kind}s sampled for {sub}")
            continue
        print(f"[probe] {sub} | {kind}s: {len(sample)} rows")

        for s in sleeps:
            ok = err429 = other = 0
            t0 = time.perf_counter()
            for r in tqdm(sample, leave=False, desc=f"{kind} sleep={s:.2f}", unit="row"):
                try:
                    resp = client.moderations.create(model="omni-moderation-latest", input=r["__txt"])
                    _ = resp.results[0]
                    ok += 1
                except Exception as e:
                    msg = str(e)
                    if "429" in msg or "Too Many Requests" in msg:
                        err429 += 1
                    else:
                        other += 1
                finally:
                    if s: time.sleep(s)
            dt = max(1e-6, time.perf_counter() - t0)
            rps = ok / dt
            print(f"  {kind} sleep={s:.2f}  ok={ok}  429s={err429}  other={other}  rps={rps:.2f}")
            results.append((kind, s, ok, err429, rps))
    return results

# Example:
probe = small_speed_probe("Ninesols", rows_comment=50, rows_post=50,
                          sleeps=( 0.15, 0.12, 0.10, .05, 0.25))
print("\nSummary:", probe)

[probe] Ninesols | comments: 50 rows

  comment sleep=0.15  ok=50  429s=0  other=0  rps=2.73

  comment sleep=0.12  ok=50  429s=0  other=0  rps=2.36

  comment sleep=0.10  ok=50  429s=0  other=0  rps=3.16

  comment sleep=0.05  ok=50  429s=0  other=0  rps=3.51

  comment sleep=0.25  ok=50  429s=0  other=0  rps=2.11
[probe] Ninesols | posts: 50 rows

  post sleep=0.15  ok=50  429s=0  other=0  rps=2.61

  post sleep=0.12  ok=50  429s=0  other=0  rps=2.82

  post sleep=0.10  ok=50  429s=0  other=0  rps=2.94

  post sleep=0.05  ok=50  429s=0  other=0  rps=3.71

  post sleep=0.25  ok=50  429s=0  other=0  rps=2.18

Summary: [('comment', 0.15, 50, 0, 2.7276131581335727), ('comment', 0.12, 50, 0, 2.356467070394891), ('comment', 0.1, 50, 0, 3.158120434546005), ('comment', 0.05, 50, 0, 3.506355353571134), ('comment', 0.25, 50, 0, 2.1120028629097263), ('post', 0.15, 50, 0, 2.6144266687822264), ('post', 0.12, 50, 0, 2.8182906272455917), ('post', 0.1, 50, 0, 2.9446445763331823), ('post', 0.05, 50, 0, 3.7108964058226657), ('post', 0.25, 50, 0, 2.180923471882022)]

In [57]:
# ==== Stage 3B: Tiny-batch scorer (auto-dial) + progress + ETA for two subs ====
from pathlib import Path
import json, time, re, math
from typing import List, Dict, Any, Tuple
from openai import OpenAI
from tqdm import tqdm

client = OpenAI()
_ws = re.compile(r"\s+")

def _rec_key(r): 
    return f"t1_{r['comment_id']}" if r.get("record_type")=="comment" else f"t3_{r['post_id']}"

def _text_of(r, cap=2000):
    txt = (r.get("body") or (r.get("title") if r.get("record_type")=="post" else "") or "")
    return _ws.sub(" ", txt.strip())[:cap]

def score_file_tinybatch(
    in_path: Path,
    out_path: Path,
    state_path: Path,
    types_to_score=("comment","post"),
    init_batch: int = 4,          # You proved 0.05s is clean; start a bit aggressive
    min_batch: int = 2,
    max_batch: int = 6,
    start_sleep: float = 0.05,    # From your probe: fast & clean
    min_sleep: float = 0.00,
    max_sleep: float = 2.0,
    char_cap: int = 2000,
    limit_rows: int | None = None
) -> Tuple[int,int,int,float]:
    """
    Returns: (n_seen, n_scored_now, total_written, elapsed_seconds)
    - n_scored_now = rows that received moderation scores in this run
    - total_written = total unique keys written (scored or passthrough) so far
    Resume-safe via state_path (__keys.json).
    """
    # Load checkpoint
    done = set()
    if state_path.exists():
        try: done = set(json.loads(state_path.read_text(encoding="utf-8")))
        except: pass

    # Planned count for progress/ETA
    planned = 0
    with in_path.open("r", encoding="utf-8") as fin:
        for i, line in enumerate(fin):
            if limit_rows is not None and i >= limit_rows: break
            if not line.strip(): continue
            r = json.loads(line)
            if r.get("record_type") in types_to_score:
                planned += 1

    sleep_s = start_sleep
    batch_sz = init_batch
    n_seen = n_scored = 0

    buf_rows: List[Dict[str,Any]] = []
    buf_texts: List[str] = []

    t0 = time.perf_counter()

    def flush(pbar):
        nonlocal n_scored, sleep_s, batch_sz
        if not buf_rows: 
            return

        # Try one API call with list input
        try:
            resp = client.moderations.create(
                model="omni-moderation-latest",
                input=buf_texts
            )
            results = resp.results
            for rec, r0 in zip(buf_rows, results):
                rec.update({
                    "toxicity_flag": bool(r0.flagged),
                    "toxicity_categories": dict(r0.categories),
                    "toxicity_scores": dict(r0.category_scores),
                })
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n_scored += 1
                done.add(rec["__key"])
            # Persist checkpoint
            state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")

            # Smooth success → nudge faster & bigger (within caps)
            if batch_sz < max_batch:
                batch_sz += 1
            sleep_s = max(min_sleep, sleep_s * 0.9)

        except Exception as e:
            msg = str(e)
            if "429" in msg or "Too Many Requests" in msg or "rate" in msg.lower():
                # Rate limit → back off
                if batch_sz > min_batch:
                    batch_sz = max(min_batch, math.floor(batch_sz * 0.7))
                sleep_s = min(max_sleep, sleep_s * 1.8 + 0.2)
                time.sleep(sleep_s)
                # Keep buffer for retry later (do not clear)
                pbar.set_postfix(batch=batch_sz, sleep=round(sleep_s, 3), note="backing off")
                return
            else:
                # Non-429 error: log and pass through (rare)
                pbar.write(f"Non-429 error; passing through batch of {len(buf_rows)}: {e}")
                for rec in buf_rows:
                    fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                    done.add(rec["__key"])
                state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")
        finally:
            # Successful write or non-429 passthrough → clear buffer
            if buf_rows:
                pbar.update(len(buf_rows))
            buf_rows.clear()
            buf_texts.clear()
            if sleep_s > 0:
                time.sleep(sleep_s)
            # Update postfix with live dial
            pbar.set_postfix(batch=batch_sz, sleep=round(sleep_s, 3))

    # Open streams
    with in_path.open("r", encoding="utf-8") as fin, out_path.open("a", encoding="utf-8") as fout, \
         tqdm(total=planned, desc=f"{in_path.name} → {out_path.name} (tiny-batch)", unit="row") as pbar:

        last_eta_print = time.perf_counter()
        processed_this_run = 0

        for i, line in enumerate(fin):
            if limit_rows is not None and i >= limit_rows: break
            if not line.strip(): 
                continue
            rec = json.loads(line)
            if rec.get("record_type") not in types_to_score:
                continue

            key = _rec_key(rec)
            if key in done:
                pbar.update(1)
                continue

            n_seen += 1
            txt = _text_of(rec, cap=char_cap)
            if not txt:
                # passthrough
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                done.add(key)
                state_path.write_text(json.dumps(sorted(done)), encoding="utf-8")
                pbar.update(1)
                continue

            rec["__key"] = key
            buf_rows.append(rec)
            buf_texts.append(txt)
            processed_this_run += 1

            if len(buf_rows) >= batch_sz:
                flush(pbar)

            # periodic ETA print (every ~20s)
            now = time.perf_counter()
            if now - last_eta_print > 20 and pbar.n:
                elapsed = now - t0
                rps = max(1e-6, n_scored / elapsed)
                remaining = max(0, pbar.total - pbar.n)
                # approximate rows per batch write = ~batch_sz; estimate time left
                eta_sec = remaining / max(1e-6, rps)
                pbar.write(f"  ~throughput={rps:.2f} rows/s | ETA={eta_sec/60:.1f} min (live)")
                last_eta_print = now

        # tail flush
        if buf_rows:
            flush(pbar)

    elapsed = time.perf_counter() - t0
    total_written = len(done)
    return n_seen, n_scored, total_written, elapsed

def run_and_time(sub: str, limit_rows: int | None = None):
    in_path  = Path(f"clean_enriched_{sub}.jsonl")
    out_path = Path(f"scored_FAST_{sub}.jsonl")
    state    = Path(f"scored_FAST_{sub}.__keys.json")
    print(f"\n=== {sub} ===")
    print(f"Reading {in_path.name} → writing {out_path.name} (resume: {state.name})")
    n_seen, n_scored, n_written, elapsed = score_file_tinybatch(
        in_path=in_path,
        out_path=out_path,
        state_path=state,
        types_to_score=("comment","post"),
        init_batch=4,
        min_batch=2,
        max_batch=6,
        start_sleep=0.05,      # You can bump to 0.03 later if it stays clean
        min_sleep=0.0,
        max_sleep=1.5,
        char_cap=2000,
        limit_rows=limit_rows  # set to None for full sub after a small smoke test
    )
    print(f"{sub}: seen={n_seen:,}  scored_now={n_scored:,}  written_total={n_written:,}  elapsed={elapsed/60:.1f} min")

# -------- Run the two subs --------
# Suggestion: do a tiny smoke test first (e.g., limit_rows=1000) then remove the limit.
run_and_time("Ninesols",        limit_rows=1000)   # quick confirm at max speed
run_and_time("DarkSouls",       limit_rows=2000)   # quick confirm (bigger)
# After both look clean, re-run with limit_rows=None for the full datasets:
# run_and_time("Ninesols",  limit_rows=None)
# run_and_time("DarkSouls", limit_rows=None)

=== Ninesols ===
Reading clean_enriched_Ninesols.jsonl → writing scored_FAST_Ninesols.jsonl (resume: scored_FAST_Ninesols.__keys.json)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch):  38%|███▊      | 381/1000 [00:20<01:19,  7.74row/s, batch=4, sleep=0.2]

  ~throughput=18.45 rows/s | ETA=0.6 min (live)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch):  51%|█████     | 507/1000 [00:41<02:00,  4.10row/s, batch=6, sleep=0.126]

  ~throughput=12.00 rows/s | ETA=0.7 min (live)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch):  59%|█████▉    | 594/1000 [01:01<02:00,  3.37row/s, batch=6, sleep=0.743]

  ~throughput=9.15 rows/s | ETA=0.7 min (live)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch):  69%|██████▉   | 693/1000 [01:22<01:18,  3.92row/s, batch=4, sleep=0.85]

  ~throughput=7.88 rows/s | ETA=0.6 min (live)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch):  80%|████████  | 801/1000 [01:43<00:42,  4.68row/s, batch=6, sleep=0.307]

  ~throughput=7.31 rows/s | ETA=0.5 min (live)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch):  91%|█████████ | 910/1000 [02:04<00:19,  4.61row/s, batch=4, sleep=0.467]

  ~throughput=6.82 rows/s | ETA=0.2 min (live)

clean_enriched_Ninesols.jsonl → scored_FAST_Ninesols.jsonl (tiny-batch): 100%|██████████| 1000/1000 [02:22<00:00,  7.00row/s, batch=6, sleep=0.566]

Ninesols: seen=1,000  scored_now=928  written_total=928  elapsed=2.4 min

=== DarkSouls ===
Reading clean_enriched_DarkSouls.jsonl → writing scored_FAST_DarkSouls.jsonl (resume: scored_FAST_DarkSouls.__keys.json)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):   3%|▎         | 60/2000 [00:20<10:54,  2.96row/s, batch=6, sleep=0.592]

  ~throughput=2.28 rows/s | ETA=14.2 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):   6%|▌         | 120/2000 [00:41<09:38,  3.25row/s, batch=6, sleep=0.984]

  ~throughput=2.29 rows/s | ETA=13.7 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  11%|█▏        | 225/2000 [01:03<09:06,  3.25row/s, batch=4, sleep=1.03]

  ~throughput=2.95 rows/s | ETA=10.0 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  15%|█▌        | 303/2000 [01:23<05:05,  5.56row/s, batch=6, sleep=0.547]

  ~throughput=3.09 rows/s | ETA=9.2 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  19%|█▉        | 387/2000 [01:44<07:24,  3.62row/s, batch=6, sleep=0.752]

  ~throughput=3.17 rows/s | ETA=8.5 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  23%|██▎       | 456/2000 [02:06<08:28,  3.04row/s, batch=4, sleep=1.26]

  ~throughput=3.08 rows/s | ETA=8.4 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  27%|██▋       | 535/2000 [02:26<07:40,  3.18row/s, batch=5, sleep=0.758]

  ~throughput=3.14 rows/s | ETA=7.8 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  32%|███▏      | 645/2000 [02:48<03:48,  5.93row/s, batch=6, sleep=0.291]

  ~throughput=3.36 rows/s | ETA=6.7 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  38%|███▊      | 759/2000 [03:08<03:48,  5.44row/s, batch=6, sleep=0.363]

  ~throughput=3.55 rows/s | ETA=5.8 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  43%|████▎     | 855/2000 [03:28<02:51,  6.69row/s, batch=6, sleep=0.404]

  ~throughput=3.60 rows/s | ETA=5.3 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  48%|████▊     | 951/2000 [03:48<04:59,  3.50row/s, batch=6, sleep=0.544]

  ~throughput=3.65 rows/s | ETA=4.8 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  54%|█████▎    | 1074/2000 [04:09<02:51,  5.40row/s, batch=4, sleep=0.487]

  ~throughput=3.79 rows/s | ETA=4.1 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  58%|█████▊    | 1155/2000 [04:30<03:32,  3.98row/s, batch=6, sleep=0.738]

  ~throughput=3.75 rows/s | ETA=3.8 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  62%|██████▏   | 1236/2000 [04:50<03:11,  4.00row/s, batch=6, sleep=0.424]

  ~throughput=3.75 rows/s | ETA=3.4 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  66%|██████▋   | 1326/2000 [05:14<03:40,  3.06row/s, batch=4, sleep=1.25]

  ~throughput=3.70 rows/s | ETA=3.0 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  71%|███████▏  | 1429/2000 [05:34<02:22,  4.02row/s, batch=5, sleep=0.554]

  ~throughput=3.76 rows/s | ETA=2.5 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  76%|███████▌  | 1524/2000 [05:55<01:31,  5.19row/s, batch=6, sleep=0.59]

  ~throughput=3.78 rows/s | ETA=2.1 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  81%|████████  | 1623/2000 [06:15<01:18,  4.78row/s, batch=6, sleep=0.342]

  ~throughput=3.82 rows/s | ETA=1.6 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  86%|████████▌ | 1719/2000 [06:35<00:44,  6.31row/s, batch=6, sleep=0.448]

  ~throughput=3.84 rows/s | ETA=1.2 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  91%|█████████ | 1824/2000 [06:58<00:40,  4.32row/s, batch=4, sleep=0.551]

  ~throughput=3.85 rows/s | ETA=0.8 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch):  96%|█████████▋| 1926/2000 [07:19<00:18,  4.11row/s, batch=4, sleep=0.744]

  ~throughput=3.87 rows/s | ETA=0.3 min (live)

clean_enriched_DarkSouls.jsonl → scored_FAST_DarkSouls.jsonl (tiny-batch): 100%|██████████| 2000/2000 [07:34<00:00,  4.40row/s, batch=6, sleep=0.426]

DarkSouls: seen=2,000  scored_now=1,770  written_total=1,770  elapsed=7.6 min

In [58]:
from pathlib import Path
import pandas as pd, json, itertools

def peek_scored(sub, n=5):
    p = Path(f"scored_FAST_{sub}.jsonl")
    assert p.exists(), f"Missing: {p}"
    df = pd.read_json(p, lines=True)
    have = df["toxicity_flag"].notna().sum() if "toxicity_flag" in df.columns else 0
    print(f"{sub}: rows={len(df):,}  with_scores={have:,}")
    display(df[["record_type","author","body","toxicity_flag","toxicity_scores"]].head(n))

peek_scored("Ninesols")
peek_scored("DarkSouls")

Ninesols: rows=928  with_scores=928

,record_type,author,body,toxicity_flag,toxicity_scores
0,comment,pixel_dust457,i hated getting blitzed by that guy 🫩,False,"{'harassment': 0.1996228729168, 'harassment_th..."
1,comment,maniacalbeanstalk,yeah he’s unbeatable. and kanghui is one of th...,False,"{'harassment': 0.005977093544740001, 'harassme..."
2,comment,maniacalbeanstalk,i come back to fight eigong every couple weeks...,False,"{'harassment': 0.005799858126313001, 'harassme..."
3,comment,lalilulelmao,"mad respect to you. for me to do that, i would...",False,"{'harassment': 0.0006585020124950001, 'harassm..."
4,comment,no-championship1729,"thanks. also, does the root core database entr...",False,"{'harassment': 1.5598027633743823e-05, 'harass..."

DarkSouls: rows=1,770  with_scores=1,770

,record_type,author,body,toxicity_flag,toxicity_scores
0,comment,maximillion322,what does that have to do with anything that i...,False,"{'harassment': 0.0007843821959220001, 'harassm..."
1,comment,maximillion322,"> kaathe, and presumably the rest, seek the wo...",False,"{'harassment': 0.009685994791526, 'harassment_..."
2,comment,maximillion322,"no, it does not make sense. the opening mentio...",False,"{'harassment': 0.000104846926716, 'harassment_..."
3,comment,ntrubilla,crushing turts,True,"{'harassment': 0.00889507366112, 'harassment_t..."
4,comment,maximillion322,"no, it does not make sense. the opening mentio...",False,"{'harassment': 7.208380258812108e-05, 'harassm..."

In [59]:
# ==== Cell A: Thread-aware sampling by roots (preserve trees) ====
from pathlib import Path
import json, random
from collections import defaultdict

random.seed(42)

def sample_threads(in_path: Path, out_path: Path, max_rows: int = 20000, max_roots: int = 300):
    """
    Build a sampled dataset that preserves conversation trees:
    - Choose up to max_roots distinct root_post_id values
    - Write all rows belonging to those roots (posts + comments)
    - Stop when ~max_rows rows are written (soft cap)
    """
    assert in_path.exists(), f"Missing input: {in_path}"
    # Pass 1: map root_post_id -> row count (thread size)
    thread_sizes = defaultdict(int)
    with in_path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip(): continue
            r = json.loads(line)
            rid = r.get("root_post_id") or r.get("post_id") if r.get("record_type") == "post" else None
            if rid:
                thread_sizes[rid] += 1

    roots = list(thread_sizes.keys())
    random.shuffle(roots)
    # lightweight stratification: prefer medium+large threads to get stable tree depth metrics
    roots.sort(key=lambda rid: thread_sizes[rid], reverse=True)

    chosen = []
    rows_written = 0
    for rid in roots:
        if len(chosen) >= max_roots or rows_written >= max_rows:
            break
        chosen.append(rid)
        rows_written += thread_sizes[rid]

    chosen_set = set(chosen)

    # Pass 2: write all rows for chosen roots (and ensure the post itself is captured)
    rows_written = 0
    with in_path.open("r", encoding="utf-8") as fin, out_path.open("w", encoding="utf-8") as fout:
        for line in fin:
            if not line.strip(): continue
            r = json.loads(line)
            rid = r.get("root_post_id") or (r.get("post_id") if r.get("record_type") == "post" else None)
            if rid in chosen_set:
                fout.write(json.dumps(r, ensure_ascii=False) + "\n")
                rows_written += 1
                if rows_written >= max_rows: break

    print(f"[sample_threads] {in_path.name} → {out_path.name} | roots={len(chosen_set)}  rows≈{rows_written:,}")
    return rows_written, len(chosen_set)

# ---- Choose reasonable caps per subreddit (midterm scale) ----
caps = {
    "SkyChildrenoftheLight": dict(max_rows=2000,  max_roots=80),   # tiny; likely grabs all
    "Ninesols":               dict(max_rows=9000,  max_roots=250),
    "AlbionOnline":          dict(max_rows=15000, max_roots=250),
    "DarkSouls":             dict(max_rows=20000, max_roots=300),
    "LiesofP":               dict(max_rows=20000, max_roots=300),
    "ElderScrollsOnline":    dict(max_rows=20000, max_roots=300),
    "WoW":                   dict(max_rows=30000, max_roots=350),
    "HollowKnight":          dict(max_rows=35000, max_roots=400),
}

# Build samples for all subs from your Stage 2 outputs (clean_enriched_*.jsonl)
for sub, params in caps.items():
    src = Path(f"clean_enriched_{sub}.jsonl")
    dst = Path(f"clean_enriched_{sub}.SAMPLE.jsonl")  # <-- clearly labeled as a sample
    sample_threads(src, dst, **params)

[sample_threads] clean_enriched_SkyChildrenoftheLight.jsonl → clean_enriched_SkyChildrenoftheLight.SAMPLE.jsonl | roots=80  rows≈201
[sample_threads] clean_enriched_Ninesols.jsonl → clean_enriched_Ninesols.SAMPLE.jsonl | roots=250  rows≈2,933
[sample_threads] clean_enriched_AlbionOnline.jsonl → clean_enriched_AlbionOnline.SAMPLE.jsonl | roots=250  rows≈3,227
[sample_threads] clean_enriched_DarkSouls.jsonl → clean_enriched_DarkSouls.SAMPLE.jsonl | roots=300  rows≈3,886
[sample_threads] clean_enriched_LiesofP.jsonl → clean_enriched_LiesofP.SAMPLE.jsonl | roots=300  rows≈5,004
[sample_threads] clean_enriched_ElderScrollsOnline.jsonl → clean_enriched_ElderScrollsOnline.SAMPLE.jsonl | roots=300  rows≈6,630
[sample_threads] clean_enriched_WoW.jsonl → clean_enriched_WoW.SAMPLE.jsonl | roots=350  rows≈12,160
[sample_threads] clean_enriched_HollowKnight.jsonl → clean_enriched_HollowKnight.SAMPLE.jsonl | roots=400  rows≈4,300

In [61]:
# ==== Cell B: Score SAMPLE files with auto-dial tiny-batch (progress + ETA) ====
from pathlib import Path

# (Re-use score_file_tinybatch and run_and_time from the earlier block, but rename outputs)

def run_and_time_sample(sub: str):
    in_path  = Path(f"clean_enriched_{sub}.SAMPLE.jsonl")
    out_path = Path(f"scored_{sub}.SAMPLE.jsonl")       # <-- labeled as scored sample
    state    = Path(f"scored_{sub}.SAMPLE.__keys.json")
    print(f"\n=== {sub} (SAMPLE) ===")
    print(f"Reading {in_path.name} → writing {out_path.name} (resume: {state.name})")

    n_seen, n_scored, n_written, elapsed = score_file_tinybatch(
        in_path=in_path,
        out_path=out_path,
        state_path=state,
        types_to_score=("comment","post"),
        init_batch=4,
        min_batch=2,
        max_batch=6,
        start_sleep=0.05,      # fast and safe per your probes
        min_sleep=0.0,
        max_sleep=1.5,
        char_cap=2000,
        limit_rows=None        # score the whole SAMPLE
    )
    print(f"{sub} SAMPLE: seen={n_seen:,}  scored_now={n_scored:,}  written_total={n_written:,}  elapsed={elapsed/60:.1f} min")

# Run all subs on their SAMPLE files
for sub in [
    "SkyChildrenoftheLight","Ninesols","AlbionOnline","DarkSouls",
    "LiesofP","ElderScrollsOnline","WoW","HollowKnight"
]:
    run_and_time_sample(sub)

=== SkyChildrenoftheLight (SAMPLE) ===
Reading clean_enriched_SkyChildrenoftheLight.SAMPLE.jsonl → writing scored_SkyChildrenoftheLight.SAMPLE.jsonl (resume: scored_SkyChildrenoftheLight.SAMPLE.__keys.json)

clean_enriched_SkyChildrenoftheLight.SAMPLE.jsonl → scored_SkyChildrenoftheLight.SAMPLE.jsonl (tiny-batch): 100%|██████████| 201/201 [00:00<00:00, 145756.41row/s]

SkyChildrenoftheLight SAMPLE: seen=0  scored_now=0  written_total=201  elapsed=0.0 min

=== Ninesols (SAMPLE) ===
Reading clean_enriched_Ninesols.SAMPLE.jsonl → writing scored_Ninesols.SAMPLE.jsonl (resume: scored_Ninesols.SAMPLE.__keys.json)

clean_enriched_Ninesols.SAMPLE.jsonl → scored_Ninesols.SAMPLE.jsonl (tiny-batch):  81%|████████  | 2382/2933 [00:22<00:11, 47.09row/s, batch=4, sleep=0.202]

  ~throughput=9.93 rows/s | ETA=0.9 min (live)

clean_enriched_Ninesols.SAMPLE.jsonl → scored_Ninesols.SAMPLE.jsonl (tiny-batch): 100%|██████████| 2933/2933 [00:41<00:00, 69.92row/s, batch=4, sleep=0.666]

Ninesols SAMPLE: seen=281  scored_now=267  written_total=2,919  elapsed=0.7 min

=== AlbionOnline (SAMPLE) ===
Reading clean_enriched_AlbionOnline.SAMPLE.jsonl → writing scored_AlbionOnline.SAMPLE.jsonl (resume: scored_AlbionOnline.SAMPLE.__keys.json)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch):  28%|██▊       | 905/3227 [00:24<01:39, 23.31row/s, batch=4, sleep=1.34]

  ~throughput=2.97 rows/s | ETA=13.0 min (live)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch):  43%|████▎     | 1378/3227 [00:45<01:46, 17.38row/s, batch=6, sleep=0.422]

  ~throughput=2.94 rows/s | ETA=10.5 min (live)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch):  60%|█████▉    | 1934/3227 [01:06<00:35, 36.46row/s, batch=6, sleep=0.712]

  ~throughput=2.84 rows/s | ETA=7.6 min (live)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch):  73%|███████▎  | 2343/3227 [01:27<00:31, 28.37row/s, batch=6, sleep=1.09]

  ~throughput=2.57 rows/s | ETA=5.8 min (live)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch):  89%|████████▉ | 2865/3227 [01:47<00:10, 34.82row/s, batch=5, sleep=0.943]

  ~throughput=2.57 rows/s | ETA=2.4 min (live)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch):  98%|█████████▊| 3167/3227 [02:09<00:04, 12.53row/s, batch=6, sleep=1.22]

  ~throughput=2.42 rows/s | ETA=0.4 min (live)

clean_enriched_AlbionOnline.SAMPLE.jsonl → scored_AlbionOnline.SAMPLE.jsonl (tiny-batch): 100%|██████████| 3227/3227 [02:13<00:00, 24.23row/s, batch=6, sleep=0.984]

AlbionOnline SAMPLE: seen=387  scored_now=321  written_total=3,161  elapsed=2.2 min

=== DarkSouls (SAMPLE) ===
Reading clean_enriched_DarkSouls.SAMPLE.jsonl → writing scored_DarkSouls.SAMPLE.jsonl (resume: scored_DarkSouls.SAMPLE.__keys.json)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  11%|█         | 423/3886 [00:20<04:09, 13.87row/s, batch=6, sleep=0.687]

  ~throughput=2.10 rows/s | ETA=27.5 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  24%|██▍       | 938/3886 [00:42<03:07, 15.73row/s, batch=6, sleep=1.22]

  ~throughput=2.04 rows/s | ETA=24.1 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  36%|███▌      | 1408/3886 [01:05<03:11, 12.91row/s, batch=4, sleep=1.5]

  ~throughput=2.09 rows/s | ETA=19.8 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  47%|████▋     | 1842/3886 [01:27<04:51,  7.02row/s, batch=5, sleep=1.23]

  ~throughput=2.13 rows/s | ETA=16.0 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  64%|██████▍   | 2489/3886 [01:47<00:38, 36.35row/s, batch=6, sleep=0.901]

  ~throughput=2.25 rows/s | ETA=10.4 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  77%|███████▋  | 3007/3886 [02:07<00:22, 38.45row/s, batch=6, sleep=0.646]

  ~throughput=2.34 rows/s | ETA=6.3 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch):  84%|████████▎ | 3251/3886 [02:30<01:00, 10.53row/s, batch=4, sleep=1.5]

  ~throughput=2.14 rows/s | ETA=5.0 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch): 100%|█████████▉| 3880/3886 [02:52<00:00, 16.46row/s, batch=6, sleep=0.979]

  ~throughput=2.22 rows/s | ETA=0.1 min (live)

clean_enriched_DarkSouls.SAMPLE.jsonl → scored_DarkSouls.SAMPLE.jsonl (tiny-batch): 100%|██████████| 3886/3886 [02:54<00:00, 22.29row/s, batch=6, sleep=0.881]

DarkSouls SAMPLE: seen=466  scored_now=384  written_total=3,804  elapsed=2.9 min

=== LiesofP (SAMPLE) ===
Reading clean_enriched_LiesofP.SAMPLE.jsonl → writing scored_LiesofP.SAMPLE.jsonl (resume: scored_LiesofP.SAMPLE.__keys.json)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):   3%|▎         | 145/5004 [00:22<23:05,  3.51row/s, batch=2, sleep=1.5]

  ~throughput=1.00 rows/s | ETA=80.8 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  16%|█▌        | 790/5004 [00:45<04:58, 14.11row/s, batch=4, sleep=0.886]

  ~throughput=1.99 rows/s | ETA=35.3 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  28%|██▊       | 1391/5004 [01:07<03:17, 18.33row/s, batch=4, sleep=1.39]

  ~throughput=2.14 rows/s | ETA=28.2 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  41%|████      | 2040/5004 [01:28<02:18, 21.47row/s, batch=6, sleep=0.854]

  ~throughput=2.39 rows/s | ETA=20.7 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  52%|█████▏    | 2606/5004 [01:52<03:50, 10.41row/s, batch=4, sleep=1.32]

  ~throughput=2.38 rows/s | ETA=16.9 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  67%|██████▋   | 3362/5004 [02:13<00:31, 51.43row/s, batch=6, sleep=0.863]

  ~throughput=2.45 rows/s | ETA=11.2 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  78%|███████▊  | 3921/5004 [02:34<00:33, 32.21row/s, batch=6, sleep=0.525]

  ~throughput=2.56 rows/s | ETA=7.1 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  87%|████████▋ | 4365/5004 [02:55<00:23, 27.48row/s, batch=6, sleep=0.886]

  ~throughput=2.47 rows/s | ETA=4.3 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch):  97%|█████████▋| 4842/5004 [03:15<00:19,  8.17row/s, batch=4, sleep=1.5]

  ~throughput=2.48 rows/s | ETA=1.1 min (live)

clean_enriched_LiesofP.SAMPLE.jsonl → scored_LiesofP.SAMPLE.jsonl (tiny-batch): 100%|██████████| 5004/5004 [03:30<00:00, 23.74row/s, batch=6, sleep=1.22]

LiesofP SAMPLE: seen=606  scored_now=508  written_total=4,906  elapsed=3.5 min

=== ElderScrollsOnline (SAMPLE) ===
Reading clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → writing scored_ElderScrollsOnline.SAMPLE.jsonl (resume: scored_ElderScrollsOnline.SAMPLE.__keys.json)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  10%|▉         | 657/6630 [00:20<05:26, 18.28row/s, batch=4, sleep=0.797]

  ~throughput=3.41 rows/s | ETA=29.2 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  16%|█▌        | 1032/6630 [00:40<06:24, 14.56row/s, batch=6, sleep=1.09]

  ~throughput=2.78 rows/s | ETA=33.6 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  22%|██▏       | 1470/6630 [01:02<04:25, 19.46row/s, batch=6, sleep=1.22]

  ~throughput=2.50 rows/s | ETA=34.5 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  27%|██▋       | 1791/6630 [01:24<08:10,  9.86row/s, batch=4, sleep=1.5]

  ~throughput=2.31 rows/s | ETA=34.9 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  30%|██▉       | 1976/6630 [01:45<10:28,  7.41row/s, batch=4, sleep=1.5]

  ~throughput=2.14 rows/s | ETA=36.3 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  35%|███▌      | 2348/6630 [02:05<11:09,  6.39row/s, batch=6, sleep=1.22]

  ~throughput=2.13 rows/s | ETA=33.6 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  44%|████▍     | 2944/6630 [02:25<02:04, 29.49row/s, batch=6, sleep=0.646]

  ~throughput=2.26 rows/s | ETA=27.2 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  49%|████▉     | 3264/6630 [02:45<04:41, 11.94row/s, batch=5, sleep=1.35]

  ~throughput=2.18 rows/s | ETA=25.8 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  56%|█████▋    | 3733/6630 [03:07<03:42, 13.02row/s, batch=4, sleep=1.36]

  ~throughput=2.15 rows/s | ETA=22.5 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  62%|██████▏   | 4137/6630 [03:28<03:06, 13.36row/s, batch=4, sleep=1.5]

  ~throughput=2.13 rows/s | ETA=19.5 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  69%|██████▉   | 4570/6630 [03:51<01:53, 18.21row/s, batch=4, sleep=1.5]

  ~throughput=2.10 rows/s | ETA=16.3 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  73%|███████▎  | 4831/6630 [04:12<02:40, 11.23row/s, batch=4, sleep=1.5]

  ~throughput=2.05 rows/s | ETA=14.6 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  80%|████████  | 5306/6630 [04:33<01:26, 15.31row/s, batch=4, sleep=1.5]

  ~throughput=2.04 rows/s | ETA=10.8 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  90%|████████▉ | 5946/6630 [04:57<00:41, 16.66row/s, batch=4, sleep=0.886]

  ~throughput=2.13 rows/s | ETA=5.4 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  94%|█████████▎| 6203/6630 [05:17<00:29, 14.31row/s, batch=6, sleep=1.09]

  ~throughput=2.09 rows/s | ETA=3.4 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch):  97%|█████████▋| 6447/6630 [05:38<00:28,  6.48row/s, batch=4, sleep=1.35]

  ~throughput=2.05 rows/s | ETA=1.5 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch): 100%|█████████▉| 6627/6630 [05:59<00:00,  7.83row/s, batch=5, sleep=1.35]

  ~throughput=2.01 rows/s | ETA=0.0 min (live)

clean_enriched_ElderScrollsOnline.SAMPLE.jsonl → scored_ElderScrollsOnline.SAMPLE.jsonl (tiny-batch): 100%|██████████| 6630/6630 [06:01<00:00, 18.36row/s, batch=6, sleep=1.22]

ElderScrollsOnline SAMPLE: seen=916  scored_now=727  written_total=6,441  elapsed=6.0 min

=== WoW (SAMPLE) ===
Reading clean_enriched_WoW.SAMPLE.jsonl → writing scored_WoW.SAMPLE.jsonl (resume: scored_WoW.SAMPLE.__keys.json)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):   4%|▎         | 454/12160 [00:20<07:55, 24.64row/s, batch=6, sleep=0.684]

  ~throughput=2.28 rows/s | ETA=85.5 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):   9%|▉         | 1109/12160 [00:40<03:32, 51.93row/s, batch=6, sleep=0.434]

  ~throughput=2.83 rows/s | ETA=65.2 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  13%|█▎        | 1606/12160 [01:01<07:03, 24.90row/s, batch=6, sleep=0.815]

  ~throughput=2.65 rows/s | ETA=66.5 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  18%|█▊        | 2172/12160 [01:21<05:57, 27.97row/s, batch=6, sleep=0.592]

  ~throughput=2.77 rows/s | ETA=60.2 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  23%|██▎       | 2848/12160 [01:41<04:18, 36.08row/s, batch=6, sleep=0.412]

  ~throughput=2.83 rows/s | ETA=54.8 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  27%|██▋       | 3332/12160 [02:02<04:46, 30.76row/s, batch=6, sleep=0.774]

  ~throughput=2.75 rows/s | ETA=53.6 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  35%|███▍      | 4234/12160 [02:26<02:03, 64.02row/s, batch=4, sleep=1.25]

  ~throughput=2.70 rows/s | ETA=49.0 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  43%|████▎     | 5211/12160 [02:47<04:10, 27.78row/s, batch=4, sleep=0.904]

  ~throughput=2.73 rows/s | ETA=42.5 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  46%|████▌     | 5618/12160 [03:07<06:12, 17.56row/s, batch=6, sleep=0.717]

  ~throughput=2.69 rows/s | ETA=40.5 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  51%|█████▏    | 6234/12160 [03:28<03:49, 25.82row/s, batch=5, sleep=1.35]

  ~throughput=2.63 rows/s | ETA=37.5 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  55%|█████▌    | 6720/12160 [03:48<03:45, 24.12row/s, batch=6, sleep=0.881]

  ~throughput=2.67 rows/s | ETA=34.0 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  59%|█████▉    | 7205/12160 [04:11<07:54, 10.45row/s, batch=4, sleep=1.5]

  ~throughput=2.63 rows/s | ETA=31.4 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  62%|██████▏   | 7571/12160 [04:33<06:43, 11.37row/s, batch=4, sleep=1.5]

  ~throughput=2.54 rows/s | ETA=30.1 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  64%|██████▍   | 7828/12160 [04:55<07:11, 10.05row/s, batch=6, sleep=0.984]

  ~throughput=2.50 rows/s | ETA=28.9 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  66%|██████▋   | 8060/12160 [05:16<05:43, 11.93row/s, batch=6, sleep=0.984]

  ~throughput=2.43 rows/s | ETA=28.1 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  68%|██████▊   | 8290/12160 [05:39<09:04,  7.10row/s, batch=4, sleep=1.5]

  ~throughput=2.34 rows/s | ETA=27.6 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  76%|███████▌  | 9235/12160 [06:00<01:43, 28.26row/s, batch=6, sleep=0.818]

  ~throughput=2.40 rows/s | ETA=20.3 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  80%|███████▉  | 9708/12160 [06:20<01:32, 26.38row/s, batch=6, sleep=0.716]

  ~throughput=2.40 rows/s | ETA=17.0 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  83%|████████▎ | 10150/12160 [06:41<01:27, 23.03row/s, batch=4, sleep=1.48]

  ~throughput=2.38 rows/s | ETA=14.1 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  89%|████████▉ | 10810/12160 [07:01<01:05, 20.52row/s, batch=6, sleep=0.377]

  ~throughput=2.44 rows/s | ETA=9.2 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  93%|█████████▎| 11282/12160 [07:22<00:32, 26.86row/s, batch=6, sleep=0.73]

  ~throughput=2.44 rows/s | ETA=6.1 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  96%|█████████▌| 11701/12160 [07:46<00:38, 11.79row/s, batch=4, sleep=1.49]

  ~throughput=2.40 rows/s | ETA=3.2 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch):  98%|█████████▊| 11959/12160 [08:07<00:24,  8.15row/s, batch=4, sleep=1.5]

  ~throughput=2.36 rows/s | ETA=1.4 min (live)

clean_enriched_WoW.SAMPLE.jsonl → scored_WoW.SAMPLE.jsonl (tiny-batch): 100%|██████████| 12160/12160 [08:23<00:00, 24.13row/s, batch=6, sleep=1.22]

WoW SAMPLE: seen=1,408  scored_now=1,181  written_total=11,933  elapsed=8.4 min

=== HollowKnight (SAMPLE) ===
Reading clean_enriched_HollowKnight.SAMPLE.jsonl → writing scored_HollowKnight.SAMPLE.jsonl (resume: scored_HollowKnight.SAMPLE.__keys.json)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  23%|██▎       | 970/4300 [00:20<02:13, 24.96row/s, batch=4, sleep=0.774]

  ~throughput=3.92 rows/s | ETA=14.2 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  30%|███       | 1309/4300 [00:42<09:02,  5.51row/s, batch=6, sleep=0.555]

  ~throughput=3.34 rows/s | ETA=14.9 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  34%|███▍      | 1468/4300 [01:04<10:49,  4.36row/s, batch=6, sleep=0.217]

  ~throughput=3.74 rows/s | ETA=12.6 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  37%|███▋      | 1607/4300 [01:24<04:32,  9.90row/s, batch=6, sleep=0.382]

  ~throughput=3.75 rows/s | ETA=12.0 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  41%|████      | 1745/4300 [01:45<06:43,  6.33row/s, batch=6, sleep=0.514]

  ~throughput=3.76 rows/s | ETA=11.3 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  43%|████▎     | 1852/4300 [02:05<11:42,  3.48row/s, batch=6, sleep=0.368]

  ~throughput=3.65 rows/s | ETA=11.2 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  46%|████▌     | 1982/4300 [02:25<06:09,  6.27row/s, batch=6, sleep=0.607]

  ~throughput=3.64 rows/s | ETA=10.6 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  50%|████▉     | 2145/4300 [02:47<07:21,  4.88row/s, batch=4, sleep=0.755]

  ~throughput=3.72 rows/s | ETA=9.7 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  91%|█████████▏| 3925/4300 [03:07<00:03, 103.53row/s, batch=5, sleep=1.35]

  ~throughput=3.57 rows/s | ETA=1.8 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch):  98%|█████████▊| 4228/4300 [03:28<00:09,  7.71row/s, batch=6, sleep=0.717]

  ~throughput=3.52 rows/s | ETA=0.4 min (live)

clean_enriched_HollowKnight.SAMPLE.jsonl → scored_HollowKnight.SAMPLE.jsonl (tiny-batch): 100%|██████████| 4300/4300 [03:34<00:00, 20.02row/s, batch=5, sleep=1.34]

HollowKnight SAMPLE: seen=843  scored_now=735  written_total=4,192  elapsed=3.6 min